baseURL: https://www.thatsnotmetalarchive.com/
languageCode: en-gb
title: That's Not Metal Archive
disableLiveReload: true

params:
  twitter: https://twitter.com/notmetalpod
  facebook: https://www.facebook.com/thatsnotmetalpodcast/
  description: >
    This site is an unofficial collection of show notes and links from the Thatâ€™s
    Not Metal podcast.
